language: cpp
osx_image: xcode8
xcode_project: apps/myApps/DepthTracker/DepthTracker.xcodeproj 
xcode_scheme: test
env:
  global:
    - LC_CTYPE=en_US.UTF-8
git:
  submodules: false
branches:
  only:
    - master
cache:

before_install:
  - git submodule update --init --recursive
notifications:
  email: false

os:
  osx
