language: cpp
osx_image: xcode8
env:
  global:
    - LC_CTYPE=en_US.UTF-8
git:
  submodules: false
branches:
  only:
    - master
cache:

before_install:
  - git submodule update --init --recursive
  - python download_of.py
script:
  - xcodebuild -project apps/myApps/DepthTracker/DepthTracker.xcodeproj -scheme test 
notifications:
  email: false
os:
  osx
